config/routes.rb
Alpha::Application.routes.draw do

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :people
  resources :movies
  resources :relationships, :only => [:create, :destroy]

  root :to => "pages#home"

  match 'movies/:id/add_relationship', :as => "add_relationship", :to => "movies#add_relationship"
  match 'users/:id/promote', :as => "user_promote", :to => "users#promote"
  match 'users/:id/demote', :as => "user_demote", :to => "users#demote"
  match '/about', :to => "pages#about"
  match '/contact', :to => "pages#contact"
  match '/signup', :to => "users#new"
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

end

app/models/person.rb
# == Schema Information
#
# Table name: people
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  birthdate  :datetime
#  imdb_id    :integer
#  created_at :datetime
#  updated_at :datetime
#

class Person < ActiveRecord::Base
  attr_accessible :name, :birthdate, :imdb_id

  has_many :relationships, :dependent => :destroy
  has_many :movies, :through => :relationships
  has_many :movies_directed, :through => :relationships, :class_name => "Movie",
    :conditions => ['relationships.role = ?', "director" ], :source => :movie
  has_many :movies_acted, :through => :relationships, :class_name => "Movie",
    :conditions => ['relationships.role = ?', "actor"], :source => :movie
  
  scope :acting, :conditions => ['relationships.role = ?', "actor"] 
  scope :directing, :conditions => ['relationships.role = ?', "director"] 
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_filter :have_to_be_admin, :only => [:new, :create, :edit, :update, :destroy]

  def new
    @title = "New person"
    @person = Person.new
    respond_to do |format|
      format.js { render_to_facebox }
    end
  end

  def create
    @person = Person.new(params[:person])
    respond_to do |format|
      if @person.save
        format.js do
          flash[:success] = "Person created"
          redirect_from_facebox @person
        end
      end
    end
  end

  def index
    @people = Person.all
    @title = "List of people"
    @aside = { :type => "people",
              :content => Person.order("birthdate").first(10) }
  end

  def show
    @person = Person.find_by_id(params[:id])
    @title = @person.name
  end

  def edit
    @person = Person.find_by_id(params[:id])
    @title = "Edit #{@person.name}"
  end

  def update
    @person = Person.find_by_id(params[:id])
    if @person.update_attributes(params[:person])
      redirect_to @person, :notice => "Person info updated"
    else
      @title = "Edit person"
      render 'edit'
    end
  end

  def destroy
    if Person.find_by_id(params[:id]).destroy
      redirect_to people_path, :notice => "Person deleted."
    end
  end

end

app/helpers/people_helper.rb
module PeopleHelper
  def age(dob)
    now = Time.now.utc.to_date
    now.year - dob.year - ((now.month > dob.month || (now.month == dob.month && now.day >= dob.day)) ? 0 : 1)
  end

end

app/views/people/_person.html.erb
<li>
  <b><%= link_to person.name, person_path(person.id) %></b>
</li>

app/views/people/edit.html.haml
%h1 Edit person
= simple_form_for(@person) do |f|
  = f.input :name
  = f.input :birthdate, :as => :date, :start_year => 1900, :end_year => Date.today.year
  = f.input :imdb_id, :label => "IMDb ID"
  = f.button :submit

app/views/people/index.html.haml
- if signed_in? && current_user.admin?
  = link_to "New person", new_person_path, :class => "button icon add", :remote => true
%h3 All people
%ul
  = render @people

app/views/people/new.html.haml
%h3 Add new person
= simple_form_for @person do |f|
  = f.input :name
  = f.input :birthdate, :as => :date, :start_year => 1900, :end_year => 2011
  = f.input :imdb_id
  = f.button :submit

app/views/people/new.js.haml
%h3 Add new person
= simple_form_for(:person, :url => people_path, :remote => true) do |f|
  = f.input :name
  = f.input :birthdate, :as => :date, :start_year => 1900, :end_year => 2011
  = f.input :imdb_id
  = f.button :submit

app/views/people/show.html.haml
- if signed_in? && current_user.admin?
  .button-group
    = link_to "Edit", edit_person_path(@person), :class => "button icon edit"
    = link_to "Delete", @person, :method => :delete, :class => "button danger icon trash", :confirm => "You sure?", :title => "Delete person"
%h3
  = @person.name
%p
  = "Born: " + @person.birthdate.strftime("%B %d, %Y")
%p
  = "Age: " + age(@person.birthdate).to_s
%p
  IMDb:
  = link_to imdb_link(@person.imdb_id, "person"), imdb_link(@person.imdb_id, "person")
- unless @person.movies.acted.blank?
  %table
    %caption Acting roles
    %thead
      %tr
        %th Movie
        %th Rating
        %th Year
        - if signed_in? && current_user.admin?
          %th Action
    %tbody
      - Relationship.where(['role = ?', "actor"]).find_all_by_person_id(@person.id).each do |r|
        %tr
          %td #{link_to(r.movie.name, movie_path(r.movie.id))}
          %td #{r.movie.rating}/10
          %td #{r.movie.year}
          -if signed_in? && current_user.admin?
            %td #{link_to("Delete", r, :method => :delete, :class => "button pill danger icon trash", :confirm => "You sure?")}
- unless @person.movies.directed.blank?
  %table
    %caption Directing roles
    %thead
      %tr
        %th Movie
        %th Rating
        %th Year
        - if signed_in? && current_user.admin?
          %th Action
    %tbody
      - Relationship.where(['role = ?', "director"]).find_all_by_person_id(@person.id).each do |r|
        %tr
          %td #{link_to(r.movie.name, movie_path(r.movie.id))}
          %td #{r.movie.rating}/10
          %td #{r.movie.year}
          -if signed_in? && current_user.admin?
            %td #{link_to("Delete", r, :method => :delete, :class => "button pill danger icon trash", :confirm => "You sure?")}