config/routes.rb
Alpha::Application.routes.draw do

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :people
  resources :movies
  resources :relationships, :only => [:create, :destroy]

  root :to => "pages#home"

  match 'movies/:id/add_relationship', :as => "add_relationship", :to => "movies#add_relationship"
  match 'users/:id/promote', :as => "user_promote", :to => "users#promote"
  match 'users/:id/demote', :as => "user_demote", :to => "users#demote"
  match '/about', :to => "pages#about"
  match '/contact', :to => "pages#contact"
  match '/signup', :to => "users#new"
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_filter :have_to_be_admin, :only => [:new, :create, :edit, :update,
    :destroy]
  
  def new
    @title = "New movie"
    @movie = Movie.new
    respond_to do |format|
      format.js { render_to_facebox }
    end
  end

  def create
    @movie = Movie.new(params[:movie])
    respond_to do |format|
      if @movie.save
        format.js do
          flash[:success] = "Movie created"
          redirect_from_facebox @movie
        end
      end
    end
  end

  def show
    @movie = Movie.find_by_id(params[:id])
    @actors = Relationship.actor.find_all_by_movie_id(params[:id])
    @directors = Relationship.director.find_all_by_movie_id(params[:id])
    @title = @movie.name
  end

  def index
    @title = "List of movies"
    @movies = Movie.paginate(:page => params[:page])
  end

  def edit
    @movie = Movie.find_by_id(params[:id])
    @title = "Edit #{@movie.name}"
  end

  def update
    @movie = Movie.find(params[:id])
    if @movie.update_attributes(params[:movie])
      flash[:success] = "Movie info updated"
      redirect_to @movie
    else
      @title = "Edit movie"
      render 'edit'
    end
  end

  def destroy
    Movie.find(params[:id]).destroy
    flash[:success] = "Movie deleted."
    redirect_to movies_path
  end

  def add_relationship
    @rel = Relationship.new
    @movie = Movie.find_by_id(params[:id])
    @title = "Add person to #{@movie.name}"
    respond_to do |format|
      format.js { render_to_facebox }
    end
  end

end

app/helpers/movies_helper.rb
module MoviesHelper
  def rating_stars(rating)
    stars = ""
    stars << "["
    rating.times do
      stars << "x"
    end
    (10-rating).times do
      stars << "-"
    end
    stars << "]"
    return stars
  end

end

app/views/movies/_movie.html.erb
<li>
  <b><%= link_to movie.name, movie_path(movie.id) %></b> (<%= movie.year %>)
</li>

app/views/movies/add_relationship.html.haml
%h3 #{@title}
= simple_form_for(:relationship, :url => relationships_path, :remote => true)  do |f|
  = f.input :person_id, :label => "Name", :collection => Person.all
  = f.input :movie_id , :as => :hidden, :input_html => { :value => @movie.id }
  = f.input :role, :collection => ["actor", "director"], :include_blank => false
  = f.button :submit, :class => "icon approve"

app/views/movies/edit.html.haml
%h1 Edit movie
= simple_form_for(@movie) do |f|
  = f.input :name
  = f.input :year, :collection => 1900..2011
  = f.input :rating, :collection => 1..10, :as => :radio
  = f.input :watched
  = f.input :imdb_id, :label => "IMDb ID"
  = f.button :submit

app/views/movies/index.html.haml
- if signed_in? && current_user.admin?
  = link_to "Add movie", new_movie_path, :class => "button icon add", :remote => true
%h3 All movies in the database
%ul
  = render @movies
= will_paginate

app/views/movies/new.html.haml
%h3 Add new movie
= simple_form_for @movie do |f|
  = f.input :name
  = f.input :year, :collection => 1900..2011
  = f.input :rating, :as => :radio, :collection => 1..10
  = f.input :watched, :as => :boolean
  = f.input :imdb_id
  = f.button :submit

app/views/movies/new.js.haml
%h3 Add new movie
= simple_form_for(:movie, :url => movies_path, :remote => true) do |f|
  = f.input :name
  = f.input :year, :collection => 1900..2011
  = f.input :rating, :as => :radio, :collection => 1..10
  = f.input :watched, :as => :boolean
  = f.input :imdb_id
  = f.button :submit

app/views/movies/show.html.haml
- if signed_in? && current_user.admin?
  .button-group
    = link_to "Edit", edit_movie_path(@movie), :class => "button icon edit"
    = link_to "Delete", @movie, :method => :delete, :class => "button danger icon trash", :confirm => "You sure?", :title => "Delete movie"
    = link_to "Add person", add_relationship_path(@movie), :class => "button icon add", :remote => true
%h3
  = @movie.name + " (" + @movie.year.to_s + ")"
%p
  = raw(rating_stars(@movie.rating))
- if @movie.watched?
  %p You have watched this movie
= link_to imdb_link(@movie.imdb_id, "movie"), imdb_link(@movie.imdb_id, "movie")
- unless @directors.blank?
  %table
    %caption Directors
    %thead
      %tr
        %th Name
        - if signed_in? && current_user.admin?
          %th Action
    %tbody
      - @directors.each do |r|
        %tr
          %td #{link_to(r.person.name, person_path(r.person_id))}
          - if signed_in? && current_user.admin?
            %td #{link_to("Delete", r, :method => :delete, :class => "button pull danger icon trash", :confirm => "You sure?")}
- unless @actors.blank?
  %table
    %caption Actors
    %thead
      %tr
        %th Name
        - if signed_in? && current_user.admin?
          %th Action
    %tbody
      - @actors.each do |r|
        %tr
          %td #{link_to(r.person.name, person_path(r.person_id))}
          - if signed_in? && current_user.admin?
            %td #{link_to("Delete", r, :method => :delete, :class => "button pull danger icon trash", :confirm => "You sure?")}