config/routes.rb
Alpha::Application.routes.draw do

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :people
  resources :movies
  resources :relationships, :only => [:create, :destroy]

  root :to => "pages#home"

  match 'movies/:id/add_relationship', :as => "add_relationship", :to => "movies#add_relationship"
  match 'users/:id/promote', :as => "user_promote", :to => "users#promote"
  match 'users/:id/demote', :as => "user_demote", :to => "users#demote"
  match '/about', :to => "pages#about"
  match '/contact', :to => "pages#contact"
  match '/signup', :to => "users#new"
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                 :integer         not null, primary key
#  name               :string(255)
#  email              :string(255)
#  encrypted_password :string(255)
#  salt               :string(255)
#  admin              :boolean         default(FALSE)
#  created_at         :datetime
#  updated_at         :datetime
#

require 'digest'
class User < ActiveRecord::Base
  attr_accessor   :password
  attr_accessible :name, :email, :admin, :password, :password_confirmation

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name,    :presence => true,
                      :length   => { :maximum => 50 }
  validates :email,   :presence => true,
                      :format   => { :with => email_regex },
                      :uniqueness => { :case_sensitive => false }
  validates :password,  :presence => true,
                        :confirmation => true,
                        :length => { :within => 6..40 }

  before_save :encrypt_password

  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end

  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil if user.nil?
    return user if user.has_password?(submitted_password)
    # returns nil in case om password mismatch as the end is reached
  end

  def self.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    (user && user.salt == cookie_salt) ? user : nil
  end

  private

    def encrypt_password
      self.salt = make_salt if new_record?
      self.encrypted_password = encrypt(password)
    end

    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end

    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end

    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate, :only => [:edit, :update]
  before_filter :correct_user, :only => [:edit, :update]
  before_filter :admin_user, :only => [:destroy, :promote, :demote]
  before_filter :oneself, :only => [:destroy, :demote]
  before_filter :is_registered, :only => [:new, :create]

  def new
    @title = "Sign up"
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if gotcha_valid? && @user.save
      sign_in @user
      flash[:success] = "Welcome to Alpha! You are now signed in"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @title = "Edit user"
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      @title = "Edit user"
      render 'edit'
    end
  end
  
  def promote
    @user = User.find(params[:id])
    @user.update_attribute(:admin, true)
    flash[:success] = "Promoted to admin"
    redirect_to :back
  end

  def demote
    @user = User.find(params[:id])
    @user.update_attribute(:admin, false)
    flash[:success] = "User demoted"
    redirect_to :back
  end

  def index
    @users = User.where(['admin = ?', false])
    @admins = User.where(['admin = ?', true])
    @title = "All users"
  end

  def show
    @user = User.find(params[:id])
    @title = @user.name
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_path
  end

  private

    def authenticate
      deny_access unless signed_in?
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_path) unless signed_in? && current_user.admin?
    end

    def oneself
      redirect_to(:back) && flash[:notice] = "Cant modify yourself" if User.find(params[:id]).id == current_user.id
    end

    def is_registered
      redirect_to(root_path) && flash[:notice] = "Already registered" if signed_in?
    end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { :size => 50 })
    gravatar_image_tag(user.email.downcase, :alt => user.name,
                       :class => 'gravatar',
                       :gravatar => options)
  end
end

app/views/users/_user.html.haml
%li
  = link_to user.name, user

app/views/users/edit.html.haml
%h1 Edit user
= simple_form_for(@user) do |f|
  = f.input :name, :hint => "Your full name or screen name"
  = f.input :email, :hint => "This will serve as your login"
  = f.input :password, :hint => "Must be atleast 6 characters long"
  = f.input :password_confirmation, :label => "Confirm", :hint => "Passwords must match"
  = f.button :submit, :class => "icon approve"
%div
  = gravatar_for @user
  = link_to "change", "http://gravatar.com/emails"

app/views/users/index.html.haml
%h3 Users:
%ul
  = render @users
%h3 Admins:
%ul
  = render @admins

app/views/users/new.html.haml
%h1 Sign up form
= simple_form_for @user do |f|
  = f.input :name, :hint => "Your full name or screen name"
  = f.input :email, :hint => "This will serve as your login"
  = f.input :password, :hint => "Must be atleast 6 characters long"
  = f.input :password_confirmation, :label => "Confirm", :hint => "Passwords must match"
  = gotcha
  - if gotcha_error
    = flash.now[:error] = gotcha_error
  = f.button :submit, :class => "icon approve"

app/views/users/show.html.haml
- if signed_in? && current_user.admin?
  .button-group
    = link_to("Delete", @user, :method => :delete, :class => "button danger icon remove", :confirm => "You sure?", :title => "Delete #{@user.name}")
    - if @user.admin?
      = link_to("Demote", user_demote_path(@user), :method => :put, :class => "button icon user")
    - else
      = link_to("Promote", user_promote_path(@user), :method => :put, :class => "button icon user")
      
%h1
  = gravatar_for @user
  = @user.name
%p
  - if @user.admin?
    %p User is admin
  = @user.email