config/routes.rb
Alpha::Application.routes.draw do

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :people
  resources :movies
  resources :relationships, :only => [:create, :destroy]

  root :to => "pages#home"

  match 'movies/:id/add_relationship', :as => "add_relationship", :to => "movies#add_relationship"
  match 'users/:id/promote', :as => "user_promote", :to => "users#promote"
  match 'users/:id/demote', :as => "user_demote", :to => "users#demote"
  match '/about', :to => "pages#about"
  match '/contact', :to => "pages#contact"
  match '/signup', :to => "users#new"
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

end

app/views/layouts/_aside.html.erb
<% if !@aside.nil? %>
  <% if @aside[:type] == "movie" %>
    <%= @aside[:content].name %>
  <% end %>

  <% if @aside[:type] == "movies" %>
    Top 10 movies:
    <ul>
      <% @aside[:content].each do |movie| %>
        <li><%= link_to movie.name, movie_path(movie.id) %> (<%= movie.rating %>/10)</li>
      <% end %>
    </ul>
  <% end %>

  <% if @aside[:type] == "people" %>
    Top 10 oldest:
    <ul>
      <% @aside[:content].each do |person| %>
        <li><%= link_to person.name, person_path(person.id) %>
          (<%= age(person.birthdate) %>)</li>
      <% end %>
    </ul>
  <% end %>
<% end %>

app/views/layouts/_footer.html.haml
= link_to "About", about_path, :class => "button"
= link_to "Contact", contact_path, :class => "button icon mail"

app/views/layouts/_navigation.html.haml
%ul
  %li
    = link_to "› Movies", movies_path, :class => "button"
  %li
    = link_to "› People", people_path, :class => "button"
  %li
    = link_to "› Users", users_path, :class => "button"

%ul
  - if signed_in?
    %li 
      = link_to "› Sign out", signout_path, :class => "button"
    %li
      = link_to "› Settings", edit_user_path(current_user), :class => "button"
  - else
    %li 
      = link_to "› Sign in", signin_path, :class => "button primary", :remote => true

    %li
      = link_to "› Register", signup_path, :class => "button"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @title || "Alpha"%></title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults, 'facebox.js' %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div class="container_12">
    <div id="main-column" class="grid_8">
      <div id="main">
        <h1 id="header"><%= link_to "Alpha", root_path %></h1>
        <div id="content">
          <% flash.each do |key, value| %>
            <div class="flash <%= key %>"><%= value %></div>
          <% end %>
          
          <%= yield %>
        </div>
      </div>
    </div>
      
    <div id="nav-column" class="grid_4">
      <div id="nav">
        <%= render 'layouts/navigation' %>
        
        <p id="presentation">
          <% if signed_in? %>
            Signed in as:<br />
            <%= link_to current_user.name, user_path(current_user) %>
          <% end %>
        </p> 
        
      </div>
    </div>
  </div>
  <div class="container_12">
    <div class="grid_12" id="footer">
      <%= render 'layouts/footer' %>
    </div>
  </div>

</body>
</html>